### PR TITLE
Add extension for ITenantStore to get all child tenants

### PR DESCRIPTION
**Pull request by MikeLarah**

### CODE REVIEW

**Comment by jongeorge1** [comment]
My immediate question is "why?". Since this is just wrapping a method on the underlying `ITenantStore`, what's the value in adding it vs just using the underlying method directly?

**Comment by mwadams** [comment]
> My immediate question is "why?". Since this is just wrapping a method on the underlying `ITenantStore`, what's the value in adding it vs just using the underlying method directly?

It feels like an extension method rather than an extension to the service API itself, perhaps?

In general, we want to keep interfaces as compact as possible, and build out utility features using extension methods, except where there is an obvious opportunity for a perf improvement by rolling it into the API (when it can be migrated in and the extension/helper method left to talk to the new API and also deprecated).

**Comment by MikeLarah** [comment]
> My immediate question is "why?". Since this is just wrapping a method on the underlying `ITenantStore`, what's the value in adding it vs just using the underlying method directly?



> > My immediate question is "why?". Since this is just wrapping a method on the underlying `ITenantStore`, what's the value in adding it vs just using the underlying method directly?
> 
> It feels like an extension method rather than an extension to the service API itself, perhaps?
> 
> In general, we want to keep interfaces as compact as possible, and build out utility features using extension methods, except where there is an obvious opportunity for a perf improvement by rolling it into the API (when it can be migrated in and the extension/helper method left to talk to the new API and also deprecated).

Yes I was wondering what the criteria was between adding methods directly to interface or to extension class.

**Comment by jongeorge1** [comment]
With the change to an extension method, should this belong in `Corvus.Tenancy` now?

**Comment by MikeLarah** [comment]
> With the change to an extension method, should this belong in `Corvus.Tenancy` now?

Yes it would be a better fit to put them there.

Have created new PR in Corvus.Tenancy to move all these extensions over: https://github.com/corvus-dotnet/Corvus.Tenancy/pull/255

I will close this PR and, once the Corvus.Tenancy changes have been published, then update Marain.TenantManagement to remove the now duplicated methods.

**Pull request closed without merging**
